CREATE TABLE Comments
(
    CommentID INT PRIMARY KEY IDENTITY (1, 1),
    ContentID INT NOT NULL,
    UserID INT NOT NULL,
    CommentText TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL,
    ParentCommentID INT NULL,
    IsEdited BIT DEFAULT 0,
    IsDeleted BIT DEFAULT 0,
    LikesCount INT DEFAULT 0,
    DislikesCount INT DEFAULT 0,
    ReplyCount INT DEFAULT 0,
    IsPinned BIT DEFAULT 0,
    PinnedAt DATETIME NULL,
    EditedBy INT NULL,
    EditedAt DATETIME NULL,
    AttachmentURL NVARCHAR (1024) NULL,
    IPAddress NVARCHAR (45) NULL,
    UserAgent NVARCHAR (512) NULL,
    IsFlagged BIT DEFAULT 0,
    FlagReason NVARCHAR (255) NULL,
    FlaggedAt DATETIME NULL,
    ModeratedBy INT NULL,
    ModeratedAt DATETIME NULL,
    ModerationStatus NVARCHAR (50) DEFAULT 'pending',
    ThreadID INT NULL,
    Depth INT DEFAULT 0,
    LanguageCode NVARCHAR (10) DEFAULT 'en',
    SentimentScore FLOAT NULL,
    IsSpam BIT DEFAULT 0,
    SpamScore FLOAT NULL,
    GeoLocation NVARCHAR (255) NULL,
    DeviceType NVARCHAR (50) NULL,
    FOREIGN KEY (ContentID) REFERENCES FunnyContent (ContentID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users (UserID) ON DELETE CASCADE,
    FOREIGN KEY (ParentCommentID) REFERENCES Comments (CommentID) ON DELETE CASCADE,
    FOREIGN KEY (EditedBy) REFERENCES Users (UserID),
    FOREIGN KEY (ModeratedBy) REFERENCES Users (UserID)
);